application: watchman-161109
runtime: python27
version: 1
api_version: 1
threadsafe: true
module: default

handlers:
- url: /.*
  script: application_sample.app

- url: /worker/.*
  script: worker.app
  login: admin
